FROM microsoft/dotnet:2.2-sdk

# Set a working dir at least 2 deep. The output and intermediate output folders will be /code/obj and /code/bin
WORKDIR /src

# By copying these into the image when building it, we don't have to re-run restore everytime we launch a new container
COPY mshare_asp/MShare_ASP.csproj MShare_ASP.csproj
RUN dotnet restore
COPY mshare_asp/ .

WORKDIR /src

RUN dotnet build "MShare_ASP.csproj" -c Debug -o ../app

WORKDIR /app

COPY mshare_asp/appsettings.json appsettings.json
ENTRYPOINT dotnet MShare_ASP.dll 