FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM microsoft/dotnet:2.2-sdk AS build
WORKDIR /src
COPY ["mshare_asp/MShare_ASP.csproj", "mshare_asp/MShare_ASP.csproj"]
RUN dotnet restore "mshare_asp/MShare_ASP.csproj"
COPY . .
WORKDIR "/src/mshare_asp"
RUN dotnet build "MShare_ASP.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "MShare_ASP.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "MShare_ASP.dll"]