#########################
### build environment ###
#########################

# base image
FROM node:10.15.1 as builder

# set working directory
RUN mkdir /usr/src/app
WORKDIR /usr/src/app

ENV PATH /usr/src/app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /usr/src/app/package.json
RUN npm install
RUN npm install -g @angular/cli@1.7.1 

# add app
COPY . /usr/src/app

# start build
CMD ng serve --host 0.0.0.0

