# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "private_network", ip: "192.168.50.4"
  config.ssh.insert_key = false
  config.ssh.private_key_path = "ssh/id_rsa_mshare"
  config.ssh.private_key_path = ["ssh/id_rsa_mshare", "~/.vagrant.d/insecure_private_key"]
  config.vm.provision "file", source: "ssh/id_rsa_mshare.pub", destination: "~/.ssh/authorized_keys"
  config.vm.synced_folder "../../", "/opt/src/local/"
  config.disksize.size = '40GB'
  config.vm.provider "virtualbox" do |v|
    v.memory = 3072
    v.cpus = 2
  end
end
